### PR TITLE
Project linter set to ruff

### PR DESCRIPTION
**Pull request by RoshiniFernando**
**Situation** 😊
- Original issue was #255 
- The current requirement is to set linter to ruff because of the stunning performance.

**Method I followed**

- I installed ruff version 0.0.255 using following command. 
```
pip install ruff
```
- Added a pyproject.toml to configure ruff and used the default configuration they have mentioned in the description here. 
[Link to ruff Github Repo](https://github.com/charliermarsh/ruff)
- Changed ci3.8.yml, ci3.9.yml, CONTRIBUTING.md and setup.py from flake8 to ruff.

**Evaluation**

- I run following commands seperately.
```
ruff check /workspace/weather-tools/weather_dl
```
```
ruff check /workspace/weather-tools/weather_mv
```
```
ruff check /workspace/weather-tools/weather_sp
```
- I got only E501 Line too long errors for all three. 
- So I changed a colon in line 52 /workspace/weather-tools/weather_dl/download_pipeline/clients.py file and checked about another error that can ruff can show us like this. 
Screenshot 2023-03-15 at 10 27 47

**My final opinion**
- I think the linter ruff works fine for this weather tools project now as my knowledge. @alxmrs I hope you will check and lead me as you're doing from the beginning to do any changes with this PR. 
Thank you so much !! 😊

### CODE REVIEW

**Comment by alxmrs** [comment]
Hey Roshini! Thanks so much for the contributions. 

I think I see why this hit so many lint errors: We use a max-line-length of 120. I think we'd like to keep this convention, as to not require too many file changes. 

On that note: I think that this CL should address all link errors that `ruff` finds in this project thereafter.

**Comment by RoshiniFernando** [comment]
- I set line-length on pyproject.toml to 120. 

- Run ruff check to three main directories. 

Screenshot 2023-03-16 at 07 34 12

**Comment by alxmrs** [comment]
I'm happy to approve this PR once the CI passes. Can you take a look and see what the issue is?

**Comment by alxmrs** [comment]
Hey Roshini, it looks like conda is having trouble installing ruff. PTAL:
Screenshot 2023-04-03 at 2 13 49 PM

**Comment by RoshiniFernando** [comment]
Maybe it because of the ruff version. I'll check ❤️

**Comment by alxmrs** [comment]
Hey, this is interesting -- I'm not sure exactly why, but it seems like conda doesn't like this ruff package version either. 

https://github.com/google/weather-tools/actions/runs/4621234525/jobs/8173447586?pr=303

Can you try reproducing this locally? I will see if I can reproduce the issue a bit later on.

**Comment by RoshiniFernando** [comment]
Thanks for your suggestions. I have reproduced the issue locally. Please finds build logs on [here](https://github.com/RoshiniFernando/weather-tools/actions/runs/4625303796)

**Review by alxmrs — APPROVED** [review]
LGTM :)

**Comment by alxmrs** [comment]
Feel free to squash & merge when you're ready.

**Comment by RoshiniFernando** [comment]
Can I know how to do the squash & merge? Seems like I'm not having writing access 
to this repo @alxmrs 😊 I'm not seeing a merge button.

**Comment by alxmrs** [comment]
Sorry about that! I didn't realize.

**Comment by RoshiniFernando** [comment]
Thank you so much @alxmrs for the immense support through out this PR journey. I learnt a lot from here. Hope this project will do great in future ❤️😊

**Comment by alxmrs** [comment]
Thanks for your contribution, and you're always welcome here :)

**Comment by alxmrs** [comment]
Just used the new linter -- man, is it fast!! I'm really happy to have this change. Thank you :)

**Comment by RoshiniFernando** [comment]
Yeah that's fast! I'm so glad to hear that @alxmrs 😊 Thank you to you too ❤️

**Pull request merged**
